pc-miler:
  api:
    url: https://pcmiler.alk.com/apis/rest/v1.0/Service.svc
    key: 0D8BA43647605743A5FB4B225664EF0F

server:
  port: 1000

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/GeoData
      uuid-representation: standard
      auto-index-creation: true